### ISSUE TITLE
Can you please share the deb file? Your repo does not work anymore

### ISSUE THREAD

**Issue by foxnoodles** [friggog/NoCCSeparators#1]
Pretty much the title says it all. thank you

**Comment by UInt2048** [comment]
I compiled the latest source from you; too lazy to fix the version number in the file: [me.chewitt.noccseparators_0.0.1-1+debug_iphoneos-arm.deb.zip](https://github.com/friggog/NoCCSeparators/files/7763921/me.chewitt.noccseparators_0.0.1-1%2Bdebug_iphoneos-arm.deb.zip)

**Comment by foxnoodles** [comment]
thank you very much. Doesn't work tho :D Separators are still there iOS 9.3.5

**Comment by UInt2048** [comment]
Interesting, it's kind of weird that it's [not on their repo's source](https://github.com/friggog/website/tree/master/repo/deb_public)

**Comment by foxnoodles** [comment]
Yeah I saw that too. I had this tweak back in the day and it worked on iOS 9.X :/

**Comment by UInt2048** [comment]
@foxnoodles I compiled it with the iOS 8.4 SDK if that has anything to do with it...

**Comment by foxnoodles** [comment]
I don't think it should matter it just hooks the existing class method.  Otherwise u would've got an error or warning. I might be wrong tho

**Comment by friggog** [comment]
The code is 8 years old so really wouldn't be surprised if this method has changed name since then

I also thought I had no trace of this left anywhere (and no toolchain to build it) but amazingly I managed to find a deb buried on an old hard drive - who knows if it will work! Looks like this was compiled against 7.1

[me.chewitt.noccseparators.deb.zip](https://github.com/friggog/NoCCSeparators/files/7765018/me.chewitt.noccseparators.deb.zip)

**Comment by UInt2048** [comment]
@friggog Thanks for sharing. We were discussing this on r/LegacyJailbreak, so the context is legacy devices like my iPhone 5 on iOS 8.4.1.
